CI: Push coverage to coveralls and codecov

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -256,6 +256,24 @@ after_script:
     fi;
 
 ###############################################################################
+after_success:
+  # Only run coveralls on Travis. When running on a public Travis-CI, the
+  # repo token is automatically inferred, but to run coveralls on Shippable
+  # the repo token needs to be specified in a .coveralls.yml or as an
+  # environment variable COVERALLS_REPO_TOKEN. This should be kept hidden
+  # from public viewing, either by encrypting the token or running on a
+  # private build.
+  # We ignore coveralls failures because the coveralls server is not 100%
+  # reliable and we don't want the CI to report a failure just because the
+  # coverage report wasn't published.
+  - if [ "$TRAVIS" = "true" ] && [ "$SHIPPABLE" != "true" ]; then
+      pip install coveralls;
+      travis_retry coveralls || echo "Coveralls push failed";
+      pip install codecov;
+      travis_retry codecov || echo "Codecov push failed";
+    fi;
+
+###############################################################################
 # Steps to take before archiving on Shippable (does nothing on Travis)
 before_archive:
   # Have shippable archive the environment.yml artifact by putting it in
